### ISSUE TITLE
Do not make issues about the service being killed by the system (they will be closed)

### ISSUE THREAD

**Issue by KieronQuinn** [KieronQuinn/TapTap#354]
Due to OEMs clearly not caring and killing every background service in sight (including accessibility services - image requiring something like Tap, Tap to be able to _use_ your phone, only for it to be killed constantly) in the name of "battery optimisation", there has been an influx of issues related to the app being killed by the system.

**Please make sure you have followed the steps in the app to help prevent the service being killed by the system, including those on https://dontkillmyapp.com/, this is the only known way to prevent the app being killed**. It is also recommended you reboot your phone after running the steps for good measure, to reset any settings that may be cached. 

Beyond this, there is no magic code that can make the system not kill the app, so I **cannot** do anything about this. Therefore, issues related to this will be tagged with "Service Killed" and be closed.

**Comment by waxwepa** [comment]
After weeks of careful observation, I am 99.9% sure Samsung does not kill Tap, Tap completely, because when it does not execute the screenshot command, I nevertheless get the haptic feedback. I found out that if I reimport the app's settings, proper functionality is restored 100% of the time. I love this workaround and I was wondering if you could not implement an automatic restore, say every 30 minutes, once you know you are running on a Samsung device. Excellent work anyway. Paul

**Comment by Albire001** [comment]
Gesture is not working on my Samsung a12

**Comment by MNLierman** [comment]
I don't know, this is a lot of reports of it not working in the background. This is really because Android kills the app? Battery optimization is off, and the app is in the unrestricted bucket, thus the app should not be killed.

 Other apps are able to maintain background services just fine. One example is Tasker. I have never had an issue with Tasker getting killed in the background. All Battery optimization is turned off for Tasker, and all of my tasks run just fine, all of my profiles execute and operate perfectly without any delay. However this app, tap tap, constantly is closing and ceasing to work, requiring that I toggle it off and back on again. It seems a lot of these issues reports may be related to Tap Tap closing / crashing. This is my issue specifically. I was thinking of creating a tasker task that relaunches Tap Tap, however, the toggle still has to be toggled off and then back on in order for it to start working again. So simply launching Tap Tap again doesn't fix the issue. 

A better solution might be that Tap Tap has a function which is essentially a health check which is run periodically or when the app is launched and the main activity is opened, it can then check if the service was killed or it it's on but not running and restart it. Optionally, it could be very helpful to have a logging feature that the user can turn on and view, so they can see what Tap Tap is doing. 

This is a very important gesture to me because Samsung removed corner swipe to open Assistant. Unless I want to wear out my power key, a gesture such as Tap Tap is my only option. If I can't get this to work, my next plan was to try to replicate capturing the gesture within Tasker's capabilities. 

**Edit:** Yup, so Tap Tap targets Android 14 SDK and according to developers.google.com it must specify a foreground service type. Tap Tap does not do this, hence the constant crashing.
Dev: it seems like this would be a simple solution. Google says the Foreground Service Type was introduced in Android 10. I'm willing to bet that if the service type is defined, Android is not going to kill the service. It's targeting spam, but if it's defined, it won't kill it. 
@KieronQuinn 

Additionally, I found some more info, specifying that foreground services can't be started from the background. Tap Tap might need to use a background service or specify a foreground type such as health monitor, something that allows it to target the accelerometer. I don't know how Tasker does it, but it's able to monitor the sensors using its service type and it launches on boot without issue. 

https://developer.android.com/develop/background-work/services/fgs/restrictions-bg-start#cases-fgs-background-starts-allowed

**Comment by KieronQuinn** [comment]
> I don't know, this is a lot of reports of it not working in the background. This is really because Android kills the app? Battery optimization is off, and the app is in the unrestricted bucket, thus the app should not be killed.
> 
> Other apps are able to maintain background services just fine. One example is Tasker. I have never had an issue with Tasker getting killed in the background. All Battery optimization is turned off for Tasker, and all of my tasks run just fine, all of my profiles execute and operate perfectly without any delay. However this app, tap tap, constantly is closing and ceasing to work, requiring that I toggle it off and back on again. It seems a lot of these issues reports may be related to Tap Tap closing / crashing. This is my issue specifically. I was thinking of creating a tasker task that relaunches Tap Tap, however, the toggle still has to be toggled off and then back on in order for it to start working again. So simply launching Tap Tap again doesn't fix the issue.

This is a strong indicator that the service was killed, since the UI thinks it's enabled but isn't. It's possible Tasker is allowed by Samsung to stay running since it's a popular app. If you're wanting to start the service from Tasker, use the broadcast intent `com.kieronquinn.app.taptap.action.START`, rather than launching the UI - but be aware that this may leave the app in a broken state due to not being able to restart the accessibility service if it was also killed.

> A better solution might be that Tap Tap has a function which is essentially a health check which is run periodically or when the app is launched and the main activity is opened, it can then check if the service was killed or it it's on but not running and restart it. Optionally, it could be very helpful to have a logging feature that the user can turn on and view, so they can see what Tap Tap is doing.

This already existed in a previous version, it made very little difference since the times the service was killed were not consistent. It's also not possible to restart accessibility services, so it made the problem worse.

> This is a very important gesture to me because Samsung removed corner swipe to open Assistant. Unless I want to wear out my power key, a gesture such as Tap Tap is my only option. If I can't get this to work, my next plan was to try to replicate capturing the gesture within Tasker's capabilities.
> 
> **Edit:** Yup, so Tap Tap targets Android 14 SDK and according to developers.google.com it must specify a foreground service type. Tap Tap does not do this, hence the constant crashing. Dev: it seems like this would be a simple solution. Google says the Foreground Service Type was introduced in Android 10. I'm willing to bet that if the service type is defined, Android is not going to kill the service. It's targeting spam, but if it's defined, it won't kill it. [@KieronQuinn](https://github.com/KieronQuinn)

The service has a type. It's in the manifest.

> Additionally, I found some more info, specifying that foreground services can't be started from the background. Tap Tap might need to use a background service or specify a foreground type such as health monitor, something that allows it to target the accelerometer. I don't know how Tasker does it, but it's able to monitor the sensors using its service type and it launches on boot without issue.
> 
> https://developer.android.com/develop/background-work/services/fgs/restrictions-bg-start#cases-fgs-background-starts-allowed

Apps which are set to unrestricted battery can still start from the background.

**Comment by MNLierman** [comment]
@KieronQuinn I appreciate your response, however, my observations are that Tap Tap in its currently released apk is in fact not specifying a Foreground Service Type as it is crashing with that exact exception.

![Screenshot_20250330_180453_LogFox.jpg](https://github.com/user-attachments/assets/c4a75162-1209-4d7f-a5c0-b5b995e46811)

Here's 2 recent crashes, I was going to say it might be related to it's Tasker plugin because that's listed in the stack, but after removing the Tasker plugin and rebooting, it still crashes with this exception. 


```
FATAL EXCEPTION: main
Process: com.kieronquinn.app.taptap, PID: 8018
android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{45c703f 8018:com.kieronquinn.app.taptap/u0a157} targetSDK=35
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5090)
	at android.os.Parcel.readParcelable(Parcel.java:5072)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3252)
	at android.os.Parcel.createException(Parcel.java:3241)
	at android.os.Parcel.readException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3166)
```

```
FATAL EXCEPTION: main
Process: com.kieronquinn.app.taptap, PID: 7450
android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{9419cdb 7450:com.kieronquinn.app.taptap/u0a157} targetSDK=35
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5090)
	at android.os.Parcel.readParcelable(Parcel.java:5072)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3252)
	at android.os.Parcel.createException(Parcel.java:3241)
	at android.os.Parcel.readException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3166)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7410)
	at android.app.Service.startForeground(Service.java:776)
	at com.joaomgcd.taskerpluginlibrary.runner.TaskerPluginRunner$Companion.startForegroundIfNeeded(TaskerPluginRunner.kt:70)
	at com.joaomgcd.taskerpluginlibrary.runner.TaskerPluginRunner$Companion.startForegroundIfNeeded$default(TaskerPluginRunner.kt:65)
	at com.joaomgcd.taskerpluginlibrary.runner.IntentServiceParallel.startForegroundIfNeeded(IntentServiceParallel.kt:25)
	at com.joaomgcd.taskerpluginlibrary.condition.IntentServiceCondition.onHandleIntent(ConditionReceivers.kt:38)
	at com.joaomgcd.taskerpluginlibrary.runner.IntentServiceParallel$onStart$1.run(IntentServiceParallel.kt:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by DaiMaZhiZaoQi** [comment]
When close  MICROPHONE permission ，will can't use

**Comment by KieronQuinn** [comment]
> When close MICROPHONE permission ，will can't use

#588

**Comment by ItsIgnacioPortal** [comment]
@KieronQuinn  To avoid being killed in the background the app must have a persistent notification. The FOSS app "Private Lock" also used to have this same issue and it was fixed by implementing a persistent notification. See: https://github.com/wesaphzt/privatelock/issues/9

**Comment by KieronQuinn** [comment]
It already does have a notification:

https://github.com/KieronQuinn/TapTap/blob/e4dce333fa8f2fe4e73bec64b52fec6dbe34ab7c/app/src/main/java/com/kieronquinn/app/taptap/service/foreground/TapTapForegroundService.kt#L93

**Comment by ItsIgnacioPortal** [comment]
Thanks for the reply @KieronQuinn 

After enabling Tap Tap (v1.6.2) there is no visible notification on GrapheneOS v2026072901 (Android 17). Notification permission is granted. After a couple days of having Tap Tap installed, the only time I saw a notification was at a random time when it was trying to start the Tap Tap service.

**Comment by KieronQuinn** [comment]
Did you perhaps hide the notification like it tells you to do? That doesn't stop it keeping the service active, it just hides it.

**Comment by ItsIgnacioPortal** [comment]
> Did you perhaps hide the notification like it tells you to do? That doesn't stop it keeping the service active, it just hides it.

@KieronQuinn No, all notification categories are enabled. I never disabled any of them. One thing I've noticed is that **the "Background Notification" category is unused (!)**. It only shows up after I tap "Show unused categories".

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/fbc38c61-510a-4d5f-a026-ec5182e654e8" />

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/12435440-8821-469b-853b-620700bb1f87" />

**Comment by ItsIgnacioPortal** [comment]
These are the notification settings of those categories. They are at their default settings.

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/d08aa1e5-aed4-42c0-a4ca-a63819f3de2d" />

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/84b4131c-561d-4a1c-b6e6-bf8bc50ac8cc" />

**Comment by KieronQuinn** [comment]
Then I do not know why your device is not showing the service notification. It won't make a difference anyway, since the notification showing is purely cosmetic - so long as the call to start foreground works it has the same effect.

**Comment by ItsIgnacioPortal** [comment]
> Then I do not know why your device is not showing the service notification. It won't make a difference anyway, since the notification showing is purely cosmetic - so long as the call to start foreground works it has the same effect.

According to this reply the call to start foreground is in fact <ins>not</ins> working: https://github.com/KieronQuinn/TapTap/issues/354#issuecomment-2764820144

Are PRs welcome?

**Comment by KieronQuinn** [comment]
> > Then I do not know why your device is not showing the service notification. It won't make a difference anyway, since the notification showing is purely cosmetic - so long as the call to start foreground works it has the same effect.
> 
> According to this reply the call to start foreground is in fact not working: [#354 (comment)](https://github.com/KieronQuinn/TapTap/issues/354#issuecomment-2764820144)
> 
> Are PRs welcome?

That's within the Tasker component and isn't the same as the main foreground service. The code I already linked above is calling a method that provides a foreground service type: https://github.com/KieronQuinn/TapTap/blob/master/app/src/main/java/com/kieronquinn/app/taptap/utils/extensions/Extensions%2BService.kt

It's not the issue here.
