### ISSUE TITLE
Crash when loading "App Shortcuts" list

### ISSUE THREAD

**Issue by rodrigoswz** [KieronQuinn/TapTap#466]
Magisk: Canary cbe97cdf (23018)
Sui: v12.4.0 (Zygisk)

Tap, Tap Crash Report

Version: 1.0.1 (1010)
Device: Mi 9T
API Version: 31
Fingerprint: Xiaomi/dipper/dipper:8.1.0/OPM1.171019.011/V9.5.5.0.OEAMIFA:user/release-keys

------ Stack Trace ------

```
java.lang.IllegalStateException: Can't compress a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:403)
	at android.graphics.Bitmap.compress(Bitmap.java:1419)
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$toShortcutItems$2.invokeSuspend(SettingsSharedAppShortcutsSelectorViewModel.kt:52)
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$toShortcutItems$2.invoke(SettingsSharedAppShortcutsSelectorViewModel.kt:2)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl.runWithService(TapTapShizukuServiceRepository.kt:22)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl$runWithService$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:1)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)


```

**Comment by gbarreirog** [comment]
Shizuku 12.4


Tap, Tap Crash Report

Version: 1.0.1 (1010)
Device: DN2103
API Version: 30
Fingerprint: OnePlus/DN2103EEA/OP515BL1:11/RP1A.200720.011/1640787928920:user/release-keys

------ Stack Trace ------

java.lang.IllegalStateException: Can't compress a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:438)
	at android.graphics.Bitmap.compress(Bitmap.java:1455)
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$toShortcutItems$2.invokeSuspend(SettingsSharedAppShortcutsSelectorViewModel.kt:52)
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$toShortcutItems$2.invoke(SettingsSharedAppShortcutsSelectorViewModel.kt:2)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl.runWithService(TapTapShizukuServiceRepository.kt:22)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl$runWithService$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:1)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

**Comment by lentryd** [comment]
Tap, Tap Crash Report

Version: 1.0.1 (1010)
Device: Pixel 5
API Version: 30
Fingerprint: google/redfin/redfin:11/RQ3A.210805.001.A1/7474174:user/release-keys

------ Stack Trace ------

java.lang.IllegalStateException: Can't compress a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:413)
	at android.graphics.Bitmap.compress(Bitmap.java:1430)
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$toShortcutItems$2.invokeSuspend(SettingsSharedAppShortcutsSelectorViewModel.kt:52)
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$toShortcutItems$2.invoke(SettingsSharedAppShortcutsSelectorViewModel.kt:2)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl.runWithService(TapTapShizukuServiceRepository.kt:22)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl$runWithService$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:1)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

**Comment by KieronQuinn** [comment]
I **think** this is fixed in 1.1, although I was unable to trigger it to reproduce. If it's not, reply with an updated stack trace and I'll reopen.

**Comment by rodrigoswz** [comment]
Yes, solved! The list now loads without crashes.
BUT when trying to perform the action (launch an app shortcut) nothing happens.

**Comment by KieronQuinn** [comment]
Which shortcut are you trying to use? It's working for me still

**Comment by rodrigoswz** [comment]
Sorry, I went to test again with new shortcuts and it worked perfectly. Thanks!

Tested with My Apps (Play Store) and Battery (Settings).
