### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vitaliklidy** [KieronQuinn/TapTap#473]
Crash then enable Tap tap
Log:
Tap, Tap Crash Report

Version: 1.0.1 (1010)
Device: Redmi 4X
API Version: 25
Fingerprint: Xiaomi/santoni/santoni:7.1.2/N2G47H/V11.0.2.0.NAMMIXM:user/release-keys

------ Stack Trace ------

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/IActivityManager$Stub;
	at com.kieronquinn.app.taptap.TapTap$iActivityManager$2.invoke(TapTap.kt:2)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at com.kieronquinn.app.taptap.TapTap$columbusModule$1$1$10.invoke(TapTap.kt:6)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:11)
	at org.koin.core.instance.ScopedInstanceFactory.create(ScopedInstanceFactory.kt:5)
	at org.koin.core.instance.ScopedInstanceFactory.get(ScopedInstanceFactory.kt:14)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:14)
	at org.koin.core.scope.Scope.get(Scope.kt:15)
	at com.kieronquinn.app.taptap.TapTap$columbusModule$1$1$11.invoke(TapTap.kt:4)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:11)
	at org.koin.core.instance.ScopedInstanceFactory.create(ScopedInstanceFactory.kt:5)
	at org.koin.core.instance.ScopedInstanceFactory.get(ScopedInstanceFactory.kt:14)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:14)
	at org.koin.core.scope.Scope.get(Scope.kt:15)
	at com.kieronquinn.app.taptap.TapTap$columbusModule$1$1$16.invoke(TapTap.kt:4)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:11)
	at org.koin.core.instance.ScopedInstanceFactory.create(ScopedInstanceFactory.kt:5)
	at org.koin.core.instance.ScopedInstanceFactory.get(ScopedInstanceFactory.kt:14)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:14)
	at org.koin.core.scope.Scope.get(Scope.kt:15)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService$special$$inlined$inject$default$2.invoke(ComponentCallbackExt.kt:3)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService.access$startService(TapTapForegroundService.kt:82)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService$startService$1.invokeSuspend(TapTapForegroundService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:5)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:2)
	at androidx.lifecycle.DispatchQueue$dispatchAndEnqueue$1$1.run(DispatchQueue.kt:2)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.IActivityManager$Stub" on path: DexPathList[[zip file "/data/app/com.kieronquinn.app.taptap-2/base.apk"],nativeLibraryDirectories=[/data/app/com.kieronquinn.app.taptap-2/lib/arm64, /data/app/com.kieronquinn.app.taptap-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 36 more

**Comment by KieronQuinn** [comment]
This is fixed in 1.1, though you will be unable to use Quick Tap to Snap, as it relies on this. The unused load of IActivityManager that was causing the crash on start has been removed though.
