### ISSUE TITLE
crash on poco f1

### ISSUE THREAD

**Issue by notAxion** [KieronQuinn/TapTap#482]
```
Tap, Tap Crash Report

Version: 1.0.1 (1010)
Device: POCO F1
API Version: 28
Fingerprint: Xiaomi/beryllium/beryllium:9/PKQ1.180729.001/V10.3.7.0.PEJMIXM:user/release-keys

------ Stack Trace ------

org.koin.core.error.InstanceCreationException: Could not create instance for [Scoped:'com.google.android.columbus.ColumbusServiceWrapper',scope:q:'com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:22)
	at org.koin.core.instance.ScopedInstanceFactory.create(ScopedInstanceFactory.kt:5)
	at org.koin.core.instance.ScopedInstanceFactory.get(ScopedInstanceFactory.kt:14)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:14)
	at org.koin.core.scope.Scope.get(Scope.kt:15)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService$special$$inlined$inject$default$2.invoke(ComponentCallbackExt.kt:3)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService.access$startService(TapTapForegroundService.kt:82)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService$startService$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:5)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:2)
	at androidx.lifecycle.DispatchQueue$dispatchAndEnqueue$1$1.run(DispatchQueue.kt:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Scoped:'com.google.android.columbus.ColumbusService',scope:q:'com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:22)
	at org.koin.core.instance.ScopedInstanceFactory.create(ScopedInstanceFactory.kt:5)
	at org.koin.core.instance.ScopedInstanceFactory.get(ScopedInstanceFactory.kt:14)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:14)
	at org.koin.core.scope.Scope.get(Scope.kt:15)
	at com.kieronquinn.app.taptap.TapTap$columbusModule$1$1$16$1.invoke(TapTap.kt:2)
	at com.google.android.columbus.ColumbusServiceWrapper.startService(ColumbusServiceWrapper.kt:11)
	at com.google.android.columbus.ColumbusServiceWrapper.<init>(ColumbusServiceWrapper.kt:5)
	at com.kieronquinn.app.taptap.TapTap$columbusModule$1$1$16.invoke(TapTap.kt:5)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:11)
	... 20 more
Caused by: java.lang.IllegalStateException: register failed, the sensor listeners size has exceeded the maximum limit 128
	at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:161)
	at android.hardware.SensorManager.registerListener(SensorManager.java:821)
	at com.google.android.columbus.sensors.GestureSensorImpl$GestureSensorEventListener.setListening(GestureSensorImpl.kt:11)
	at com.google.android.columbus.sensors.GestureSensorImpl.startListening(GestureSensorImpl.kt:1)
	at com.kieronquinn.app.taptap.components.columbus.TapTapColumbusService.updateSensorListener(TapTapColumbusService.kt:24)
	at com.kieronquinn.app.taptap.components.columbus.TapTapColumbusService.<init>(TapTapColumbusService.kt:12)
	at com.kieronquinn.app.taptap.TapTap$columbusModule$1$1$15.invoke(TapTap.kt:27)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:11)
	... 29 more


```

**Comment by KieronQuinn** [comment]
You have hit the maximum number of sensor listeners somehow. Reboot your device.
