### ISSUE TITLE
Crushing on Samsung

### ISSUE THREAD

**Issue by rajarshikhatua100** [KieronQuinn/TapTap#496]
Tap, Tap Crash Report

Version: 1.2 (1200)
Device: SM-M315F
API Version: 30
Fingerprint: samsung/m31nnxx/m31:11/RP1A.200720.012/M315FXXS2BUK2:user/release-keys

------ Stack Trace ------

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
	at androidx.recyclerview.widget.RecyclerView.getChildViewHolder(RecyclerView.java:1)
	at com.kieronquinn.app.taptap.ui.views.LifecycleAwareRecyclerView$Adapter.onDetachedFromRecyclerView(LifecycleAwareRecyclerView.kt:7)
	at androidx.recyclerview.widget.RecyclerView.setAdapter(RecyclerView.java:5)
	at com.kieronquinn.app.taptap.ui.screens.settings.actions.selector.SettingsActionsAddCategorySelectorFragment.handleState(SettingsActionsAddCategorySelectorFragment.kt:19)
	at com.kieronquinn.app.taptap.ui.screens.settings.actions.selector.SettingsActionsAddCategorySelectorFragment$setupState$1$1.emit(SettingsActionsAddCategorySelectorFragment.kt:3)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:11)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:8)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:30)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:1)
	at kotlinx.coroutines.selects.SelectBuilderImpl$onTimeout$$inlined$Runnable$1.run(Runnable.kt:11)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by KieronQuinn** [comment]
Fixed in 1.3
