### ISSUE TITLE
The App Crashes when trying the first time.

### ISSUE THREAD

**Issue by branperryqc** [KieronQuinn/TapTap#512]
I'll leave you the report just right here, hope you can fix it! Really enjoy your apps, DarQ is my favorite! 🙏

My device is a UMIDIGI Bison Pro on stock Android 11 (was just coming with their own launcher & a extra system setting for included macro side buttons)

Rooted with SP Flash Tool & Magisk

```
Tap, Tap Crash Report

Version: 1.3 (1300)
Device: BISON Pro
API Version: 30
Fingerprint: UMIDIGI/BISON_Pro/BISON_Pro:11/RP1A.200720.011/2105241743:user/release-keys

------ Stack Trace ------

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{552f1de u0 com.kieronquinn.app.taptap/.service.foreground.TapTapForegroundService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7700)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Comment by KieronQuinn** [comment]
Your device lagged, [the first thing the service does is to call that method](https://github.com/KieronQuinn/TapTap/blob/master/app/src/main/java/com/kieronquinn/app/taptap/service/foreground/TapTapForegroundService.kt#L96). Nothing I can do.
