### ISSUE TITLE
使用shizuku(adb模式)激活taptap快捷方式时发生崩溃

### ISSUE THREAD

**Issue by TensorABC** [KieronQuinn/TapTap#513]
mate40pro 鸿蒙2.0.0(230)rom
以下是崩溃报告:
Tap, Tap Crash Report

Version: 1.3 (1300)
Device: NOH-AN01
API Version: 29
Fingerprint: HUAWEI/NOH-AN01/HWNOH:10/HUAWEINOH-AN01/102.0.0.230C00:user/release-keys

------ Stack Trace ------

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/content/pm/ShortcutQueryWrapper;
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$getAppShortcuts$2.invokeSuspend(SettingsSharedAppShortcutsSelectorViewModel.kt:4)
	at com.kieronquinn.app.taptap.ui.screens.settings.shared.selector.appshortcuts.SettingsSharedAppShortcutsSelectorViewModelImpl$getAppShortcuts$2.invoke(SettingsSharedAppShortcutsSelectorViewModel.kt:2)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl.runWithService(TapTapShizukuServiceRepository.kt:24)
	at com.kieronquinn.app.taptap.repositories.service.TapTapShizukuServiceRepositoryImpl$runWithService$6.invokeSuspend(TapTapShizukuServiceRepository.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:11)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: java.lang.ClassNotFoundException: android.content.pm.ShortcutQueryWrapper
	... 13 more

**Comment by KieronQuinn** [comment]
Fixed in 1.4
