### ISSUE TITLE
Bug Crash app

### ISSUE THREAD

**Issue by Jeiel17** [KieronQuinn/TapTap#528]
```Tap, Tap Crash Report```

**
Version: 1.3 (1300)
Device: moto g(8) power
API Version: 30
Fingerprint: motorola/sofiar_retail/sofiar:11/RPES31.Q4U-47-35-12/24aaf7:user/release-keys
**

------ Stack Trace ------

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{442c299 u0 com.kieronquinn.app.taptap/.service.foreground.TapTapForegroundService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7755)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by KieronQuinn** [comment]
#512
