### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Mirihadeko** [KieronQuinn/TapTap#538]
Tap, Tap Crash Report

Version: 1.4 (1400)
Device: CPH2121
API Version: 31
Fingerprint: OPPO/CPH2121/OP4C51L1:12/SP1A.210812.016/Q.202206201640:user/release-keys

------ Stack Trace ------

java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.kieronquinn.app.taptap.ui.screens.settings.actions.SettingsActionsGenericAdapter.updateWhenGatesSize(SettingsActionsGenericAdapter.kt:219)
	at com.kieronquinn.app.taptap.ui.screens.settings.actions.SettingsActionsGenericFragment$setupResultListeners$2.invoke(SettingsActionsGenericFragment.kt:142)
	at com.kieronquinn.app.taptap.ui.screens.settings.actions.SettingsActionsGenericFragment$setupResultListeners$2.invoke(SettingsActionsGenericFragment.kt:140)
	at androidx.fragment.app.FragmentKt.setFragmentResultListener$lambda-0(Fragment.kt:65)
	at androidx.fragment.app.FragmentKt.$r8$lambda$i257It-r9epgOyGhyTl2zq_C8dk(Unknown Source:0)
	at androidx.fragment.app.FragmentKt$$ExternalSyntheticLambda0.onFragmentResult(Unknown Source:2)
	at androidx.fragment.app.FragmentManager$6.onStateChanged(FragmentManager.java:954)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3167)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8204)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

**Comment by Kirkalic** [comment]
Sorry, I'm busy. I'll reply shortly.

**Comment by KieronQuinn** [comment]
#478

**Comment by KieronQuinn** [comment]
> Sorry, I'm busy. I'll reply shortly.

Please turn off your auto reply for GitHub, it is getting very annoying to have to delete these comments from every issue. If it continues, you will be blocked from this repo.

**Comment by Kirkalic** [comment]
Sorry, I'm busy. I'll reply shortly.
