### ISSUE TITLE
Crash on TapTap first launch

### ISSUE THREAD

**Issue by NeverYouGetYouUp001** [KieronQuinn/TapTap#619]
TapTap crash on every first launch,and if you launch again,it don't crash untill device reboot or something....
Log:
```
Tap, Tap Crash Report

Version: 1.6.1 (1610)
Device: ANY-AN00
API Version: 33
Fingerprint: HONOR/ANY-AN00/HNANY-Q:13/HONORANY-AN00/7.1.0.218C00E208R1P3:user/release-keys

------ Stack Trace ------

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ef5763f u0 com.kieronquinn.app.taptap/.service.foreground.TapTapForegroundService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2512)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2486)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2777)
	at android.os.Handler.dispatchMessage(Handler.java:114)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.app.ActivityThread.main(ActivityThread.java:9205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2049)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:2004)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService$Companion.start(TapTapForegroundService.kt:63)
	at com.kieronquinn.app.taptap.service.foreground.TapTapForegroundService$Companion.start$default(TapTapForegroundService.kt:59)
	at com.kieronquinn.app.taptap.work.TapTapRestartWorker.doWork(TapTapRestartWorker.kt:50)
	at androidx.work.Worker$1.run(Worker.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1033)


```

**Comment by KieronQuinn** [comment]
#512
